[
    "B_Heli_Light_01_F",
    "B_T_VTOL_01_infantry_F",
    "O_Heli_Light_02_unarmed_F",
    "I_Heli_Transport_02_F",
    "I_Heli_light_03_unarmed_F",
    "O_Heli_Transport_04_bench_F",
    "B_Heli_Transport_01_F",
    "B_Heli_Attack_01_F",
    "B_Heli_Transport_03_F",
    "I_C_Heli_Light_01_civil_F"
];